####################################################################################################
##  EVE - Expressive Vector Engine
##  Copyright : EVE Project Contributors
##  SPDX-License-Identifier: BSL-1.0
####################################################################################################
name: EVE - Integration Tests
on:
  push:
    branches:
      - main
    paths:
      - cmake
      - CMakeLists.txt
      - examples
      - test

concurrency:
  group: install-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##################################################################################################
  ## Check install process of EVE via CMake
  ##################################################################################################
  install:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v7
    strategy:
      fail-fast: false

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1
      - name: Install EVE from checkout
        run: |
          mkdir build && cd build
          cmake -G Ninja .. -DEVE_BUILD_TEST=OFF -DCMAKE_CXX_COMPILER=clang++
          ninja install > /dev/null
      - name: Run Sample CMake
        run: |
          mkdir install && cd install
          cmake ../test/integration/install-test -G Ninja
          ninja && ctest --verbose

  ##################################################################################################
  ## Check install process of EVE via CPM
  ##################################################################################################
  cpm:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1
      - name: Compile using CPM
        run: |
          git config --global --add safe.directory $PWD
          mkdir install && cd install
          cmake ../test/integration/cpm-test -G Ninja -DGIT_BRANCH=${BRANCH_NAME} -DCMAKE_CXX_COMPILER=clang++ -DEVE_BUILD_TEST=OFF
          ninja && ctest --verbose

  ##################################################################################################
  ## Check install process of EVE via FetchContents
  ##################################################################################################
  fetch:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1
      - name: Compile using FetchContent
        run: |
          git config --global --add safe.directory  $PWD
          mkdir install && cd install
          cmake ../test/integration/fetch-test -G Ninja -DGIT_BRANCH=${BRANCH_NAME} -DEVE_BUILD_TEST=OFF -DCMAKE_CXX_COMPILER=clang++
          ninja && ctest --verbose

  ##################################################################################################
  ## Check EVE multi-architecture setup
  ##################################################################################################
  multi-arch:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v6
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1
      - name: Prepare EVE repository for branch ${{ github.head_ref }}
        run: |
          git config --global --add safe.directory $PWD
          mkdir build && cd build
          cmake .. -G Ninja
          ninja install > /dev/null
      - name: Test EVE multi-architecture support
        run: |
          mkdir multi-test && cd multi-test
          cmake ../examples/multi-arch -G Ninja
          ninja multi-arch
          ./multi-arch
